dlpi

diff --git a/DESLBuilder b/DESLBuilder
--- a/DESLBuilder
+++ b/DESLBuilder
@@ -126,10 +126,20 @@ RunDESLBuilderXInWorld(){
 	ClearEnvVariables '/sbin:/bin';
 	SetEnvVariables;
 
+	# Already run without FSV (Return)
+	[ "${DESLB_DISABLE_FSV:-0}" = '1' ] && {
+		mount -t tmpfs "tmp://DESLBuilder/session/${DESLB_SESSION_ID}" "/tmp" || {
+			error 'Failed to mount tmpfs in /tmp directory.'
+			return ${1};
+		}
+		PATH="${PATH_OLD}" ExecDESLBuilderX "${@}";
+		return ${?};
+	}
+
 	DESLB_RUN_IN_WORLD=1 DESLB_SH=/bin/sh chroot "${DESLB_SESSION_DIR}" /DESLBuilder/DESLBuilder "${@}"
 	local R=${?};
 
-	# Request no fs virtualization
+	# Request no fs virtualization (NO Return)
 	[ "${R}" = '251' ] && {
 		warning 'Restarting DESLBuilder without filesystem virtualization...'
 		mount -t tmpfs "tmp://DESLBuilder/session/${DESLB_SESSION_ID}" "/tmp" || {
@@ -145,6 +155,7 @@ RunDESLBuilderXInWorld(){
 ExecDESLBuilderX(){
 
 	[ "${DESL_BUILDER_X}" = '' ] && SHOW_RESULT_CODE=1;
+	[ ! "${DESLB_SUBPROCESS:-0}" = '0' ] && SHOW_RESULT_CODE=0;
 
 	. ${SCRIPTS_DIR}/DESLBuilderX
 	DESLB_Main "${@}"
@@ -183,7 +194,8 @@ ClearEnvVariables(){
 		IFS=' =';
 		set -- ${e}
 		case ${2} in
-			DESL_BUILDER | BUILDER_ARCH* | TERM | PWD) ;;
+			'') ;;
+			DESL_BUILDER | BOOTSTRAP_ARCH* | TERM | PWD) ;;
 			DESLB_*);;
 #			*_DIR);;
 			PATH ) PATH_OLD="${PATH}";;
@@ -206,7 +218,7 @@ LoadDirectorySettings(){
 	export IMAGE_ROOT_DIR="${ROOT_DIR}/bin";
 	export BUILD_ROOT_DIR="${ROOT_DIR}/build";
 	export TOOLCHAIN_ROOT_DIR="${ROOT_DIR}/toolchain";
-	export BOOTSTRAP_ROOT_PREFIX="${ROOT_DIR}/toolchain/build";
+	export BOOTSTRAP_ROOT_PREFIX="${ROOT_DIR}/toolchain/bootstrap";
 
 	export ETC_DIR="${SCRIPTS_DIR}/etc";
 
@@ -220,9 +232,9 @@ GenerateSessionID(){
 }
 
 SetDirectoryWithArch(){
-	export BOOTSTRAP_DIR="${BOOTSTRAP_ROOT_PREFIX}-${BUILDER_ARCH}/bootstrap-${BUILDER_ARCH}";
+	export BOOTSTRAP_DIR="${BOOTSTRAP_ROOT_PREFIX}-${BOOTSTRAP_ARCH}/core-${BOOTSTRAP_ARCH}";
 
-	export DBSE_DIR="${BOOTSTRAP_ROOT_PREFIX}-${BUILDER_ARCH}/DBSE";
+	export DBSE_DIR="${BOOTSTRAP_ROOT_PREFIX}-${BOOTSTRAP_ARCH}/DBSE";
 	export CORETOOLS_DIR="${DBSE_DIR}/coretools";
 }
 
@@ -256,12 +268,12 @@ DetectBuilderArch(){
 		warning 'DESLBuilder may not be supported by your shell or environment.'
 	}
 
-	export BUILDER_ARCH_ORG=${T1};
-	export BUILDER_ARCH_ORG_T3=${T3}; # Not used: DESLBuilder v2 or later can run under DESLinux only.
-	export BUILDER_ARCH=${T1};
-	case ${BUILDER_ARCH} in
-		i686	) BUILDER_ARCH='x86';;
-		x86_64	) BUILDER_ARCH='x64';;
+	export BOOTSTRAP_ARCH_ORG=${T1};
+	export BOOTSTRAP_ARCH_ORG_T3=${T3}; # Not used: DESLBuilder v2 or later can run under DESLinux only.
+	export BOOTSTRAP_ARCH=${T1};
+	case ${BOOTSTRAP_ARCH} in
+		i686	) BOOTSTRAP_ARCH='x86';;
+		x86_64	) BOOTSTRAP_ARCH='x64';;
 	esac
 
 	return 0;
diff --git a/scripts/ExecBuildScript b/scripts/ExecBuildScript
--- a/scripts/ExecBuildScript
+++ b/scripts/ExecBuildScript
@@ -68,8 +68,15 @@ PrepareBuildDirectory(){ # build_dir, shared_dir
 	local R_DIR="${2}";
 	mkdir -p "${W_DIR}"
 
+	export SHARED_SOURCE_DIR='-';
+	[ ! "${Package_ImportCoreInfo:--}" = '-' ] && {
+		vinfo 'This package imports CoreInfo'
+		DESLBP_GetSharedDirectory "${Package_ImportCoreInfo}";
+		return 0;
+	}
 	[ "${DESLB_SUPPORT_NATIVE_ISOLATION:-0}" = '1' ] && {
 		vinfo 'This package supports native isolation'
+		SHARED_SOURCE_DIR="${R_DIR}";
 		return 0;
 	}
 
@@ -89,19 +96,106 @@ PrepareBuildDirectory(){ # build_dir, shared_dir
 }
 
 MakeDLP(){
-
+	local DLP_ROOT_DIR="${DLP_DEST_DIR}/root";
 	[ ! -e "${DLP_INSTALL_DIR}" ] && {
 		vinfoex "No files are installed."
 		return 0;
 	}
 
-	find $DLP_INSTALL_DIR
+	local BaseSystem='';
+	[ "${PACKAGE_ROOT_CATEGORY}" = 'bootstrap' ] && BaseSystem='/BaseSystem:DESLBuilder';
+	mkdir -p "${DLP_ROOT_DIR}/"
 
-	error "${SCRIPTS_DIR}/dlpi" /Create /Dir:"${DLP_INSTALL_DIR}" \
-		/Script:"${CURRENT_PACKAGE_DIR}/DESLPackage.sh" \
-		/MetaData:"${CURRENT_PACKAGE_DIR}/DESLPackage.def" \
-		/DataType:DLP || return ${?};
+	{ # doc
+		local M=0;
+		mkdir -p "${DLP_ROOT_DIR}/share"
+		[ -e "${DLP_INSTALL_DIR}/share/doc" ] && {
+			mv "${DLP_INSTALL_DIR}/share/doc" "${DLP_ROOT_DIR}/share" || return ${?};
+			M=1;
+		}
+		[ -e "${DLP_INSTALL_DIR}/share/man" ] && {
+			mv "${DLP_INSTALL_DIR}/share/man" "${DLP_ROOT_DIR}/share" || return ${?};
+			M=1;
+		}
+		[ -e "${DLP_INSTALL_DIR}/share/info" ] && {
+			mv "${DLP_INSTALL_DIR}/share/info" "${DLP_ROOT_DIR}/share" || return ${?};
+			M=1;
+		}
+
+		# remove share/ if empty
+		rmdir "${DLP_INSTALL_DIR}/share/" 2>/dev/null
+		rmdir "${DLP_ROOT_DIR}/share/" 2>/dev/null
+
+		[ "${M}" = '1' ] && {
+			RunDLPI /Create /Dir:"${DLP_ROOT_DIR}" /PackageDef:"${PACKAGES_DIR}/${DESL_BUILD_PACKAGE}/DESLPackage.def" /Platform:${DESL_ARCH} /ID:${DESL_BUILD_PACKAGE} /SaveTo:"${Package_Category}/${Package_ID}-doc_${Package_ID_Suffix}_${DESL_ARCH}.dlp" ${BaseSystem} || return ${?};
+			rm -rf "${DLP_ROOT_DIR}" || return ${?};
+			mkdir -p "${DLP_ROOT_DIR}" || return ${?};
+		}
+
+	}
+
+	{ # dev
+		local M=0;
+		local x p;
+		mkdir -p "${DLP_ROOT_DIR}/lib"
+
+		[ -e "${DLP_INSTALL_DIR}/include" ] && {
+			mv "${DLP_INSTALL_DIR}/include" "${DLP_ROOT_DIR}" || return ${?};
+			M=1;
+		}
+
+		[ -e "${DLP_INSTALL_DIR}/lib/pkgconfig" ] && {
+			mv "${DLP_INSTALL_DIR}/lib/pkgconfig" "${DLP_ROOT_DIR}/lib" || return ${?};
+			M=1;
+		}
+
+		for x in `find "${DLP_INSTALL_DIR}" -name "*.a"`; do
+			p="${DLP_ROOT_DIR}/${x#${DLP_INSTALL_DIR}}";
+			mkdir -p "${p%/*}" || return ${?};
+			mv "${x}" "${p}" || return ${?};
+			M=1;
+		done
+
+		# remove share/ if empty
+		rmdir "${DLP_ROOT_DIR}/include/" 2>/dev/null
+		rmdir "${DLP_ROOT_DIR}/lib/" 2>/dev/null
+
+		[ "${M}" = '1' ] && {
+			RunDLPI /Create /Dir:"${DLP_ROOT_DIR}" /PackageDef:"${PACKAGES_DIR}/${DESL_BUILD_PACKAGE}/DESLPackage.def" /Platform:${DESL_ARCH} /ID:${DESL_BUILD_PACKAGE} /SaveTo:"${Package_Category}/${Package_ID}-dev_${Package_ID_Suffix}_${DESL_ARCH}.dlp" ${BaseSystem} || return ${?};
+			rm -rf "${DLP_ROOT_DIR}" || return ${?};
+			mkdir -p "${DLP_ROOT_DIR}" || return ${?};
+		}
+
+	}
+
+	# Cleanup
+	for x in `find "${DLP_INSTALL_DIR}" -name "*.la"`; do
+		rm "${x}" || return ${?};
+		rmdir "${x%/*}" 2>/dev/null
+	done
+
+	CheckEmptyDir "${DLP_INSTALL_DIR}" && {
+		warning "No main files found to install."
+	} || {
+		RunDLPI /Create /Dir:"${DLP_INSTALL_DIR}" /PackageDef:"${PACKAGES_DIR}/${DESL_BUILD_PACKAGE}/DESLPackage.def" /Platform:${DESL_ARCH} /ID:${DESL_BUILD_PACKAGE} /SaveTo:"${Package_Category}/${Package_ID}_${Package_ID_Suffix}_${DESL_ARCH}.dlp" || return ${?};
+	}
+
 	return 0;
+}
+
+RunDLPI(){
+	case ${DESLB_RUN_IN_WORLD} in
+		1) DESLB_SUBPROCESS=1 "${SCRIPTS_DIR}/dlpi" "${@}" || return ${?};;
+		*) DESLB_SUBPROCESS=1 "${CORETOOLS_DIR}/sh" "${SCRIPTS_DIR}/dlpi" "${@}" || return ${?};;
+	esac
+	return 0;
+}
+
+CheckEmptyDir(){
+	local P="${1}";
+	set -- ${1}/*
+	[ "${P}/*" = "${1}" ] && return 0;
+	return 1;
 }
 
 error(){
diff --git a/scripts/SetupScriptEngine b/scripts/SetupScriptEngine
--- a/scripts/SetupScriptEngine
+++ b/scripts/SetupScriptEngine
@@ -24,7 +24,7 @@ build_se(){
 	local BB_SRC_URL="${BB_SRC_BASE}/${BB_SRC_FILE}.${BB_SRC_EXT}";
 	local BB_SRC_LOCAL="${DL_CACHE_DIR}/${BB_SRC_FILE}.${BB_SRC_EXT}";
 
-	local BB_BUILD_DIR_BASE="${BUILD_ROOT_DIR}/builder-${BUILDER_ARCH}/";
+	local BB_BUILD_DIR_BASE="${BUILD_ROOT_DIR}/bootstrap-${BOOTSTRAP_ARCH}/";
 	local BB_BUILD_DIR="${BB_BUILD_DIR_BASE}/${BB_SRC_FILE}";
 
 	[ ! -e "${BB_SRC_LOCAL}" ] && {
@@ -57,10 +57,14 @@ build_se(){
 			echo "E: Failed to config."
 			return 4;
 		}
-		make -j4 || {
-			echo "E: Failed to build."
-			echo "E: Please install standard build tools for your system."
-			return 5;
+
+		local n=$(nproc);
+		make -j$((n+2)) || {
+			make || {
+				echo "E: Failed to build."
+				echo "E: Please install standard build tools for your system."
+				return 5;
+			}
 		}
 		cd "${ODIR}"
 	}
@@ -76,8 +80,8 @@ build_se(){
 }
 
 download_se(){
-	local BB_BIN_LOCAL="${DL_CACHE_DIR}/${BB_BIN_FILE}${BUILDER_ARCH_ORG}";
-	local BB_BIN_URL="${BB_BIN_BASE}/${BB_BIN_FILE}${BUILDER_ARCH_ORG}";
+	local BB_BIN_LOCAL="${DL_CACHE_DIR}/${BB_BIN_FILE}${BOOTSTRAP_ARCH_ORG}";
+	local BB_BIN_URL="${BB_BIN_BASE}/${BB_BIN_FILE}${BOOTSTRAP_ARCH_ORG}";
 
 	echo 'I: Downloading busybox pre-built binary...'
 
