RC: Many packages are buildable, Not linux

diff --git a/scripts/DESLBuilderX b/scripts/DESLBuilderX
--- a/scripts/DESLBuilderX
+++ b/scripts/DESLBuilderX
@@ -3,8 +3,9 @@
 # Always run as vroot with cleaned environemnt variable (But not in DESLBWorld)
 
 DESLB_Main(){
-
-	[ "${DESLB_STARTUP_PATH}" = '' ] && DESLB_STARTUP_PATH="${PATH}";
+	[ "${DESLB_STARTUP_PATH}" = '' ] && {
+		export DESLB_STARTUP_PATH="${PATH}";
+	}
 	PATH="${DESLB_STARTUP_PATH}";
 
 	# DESLBuilderX marker
@@ -72,23 +73,29 @@ DESLB_Main(){
 		AddPATH "${TOOLCHAIN_DIR}" "${TOOLCHAIN_USR_DIR}" "${TOOLCHAIN_TOOLS_DIR}" "${TOOLCHAIN_LOCAL_DIR}" "${TOOLCHAIN_BUILDER_DIR}"
 
 		[ ! -e '/lib' ] && [ ! -L '/lib' ] && ln -s "${TOOLCHAIN_BUILDER_DIR}/lib" /lib
-		[ ! -e '/usr' ] && [ ! -L '/usr' ] && ln -s "${TOOLCHAIN_BUILDER_DIR}/usr" /usr
-	} || {
-		PATH="${PATH}:${BOOTSTRAP_DIR}/bin";
+		[ ! -e '/usr' ] && [ ! -L '/usr' ] && ln -s "${TOOLCHAIN_TOOLS_DIR}" /usr
 	}
 
 	case "${PACKAGE_ROOT_CATEGORY}" in
 		'toolchain-base' )
 			# Add bootstrap
 			AddPATH "${BOOTSTRAP_DIR}"
-			AddPATH "${BASE_TOOLCHAIN_DIR}"
+			AddPATH "${TOOLCHAIN_BASEARCH_DIR}"
 		;;
 		'toolchain' )
 			# Add bootstrap
-			AddPATH "${BASE_TOOLCHAIN_DIR}"
+			AddPATH "${TOOLCHAIN_BASEARCH_DIR}"
 			AddPATH "${BOOTSTRAP_DIR}"
 		;;
 	esac
+
+	# Exception: Building 'make' requires 'Make', 'MakeCPIO' requires 'MakeCPIO'.
+	case "${DESL_BUILD_PACKAGE}" in
+		'toolchain/tools' ) export DESL_BUILDING_CORE_TOOLS=1;;
+	esac
+	[ "${DESL_BUILDING_CORE_TOOLS:-0}" = '1' ] && {
+		AddPATH "${BOOTSTRAP_DIR}";
+	}
 
 	# Command
 	. "${INCLUDES_DIR}/DESLBuilder.sh"
@@ -161,6 +168,9 @@ GetTargetArch(){
 		DESL_INTERNAL_TOOLS=1;
 	}
 
+	# Backup
+	export DESL_ARCH_ORG=${DESL_ARCH};
+
 	# Convert DESL_ARCH to internal format
 	export DESL_ARCH_BUILD=${DESL_ARCH};
 	case ${DESL_ARCH_BUILD} in
@@ -201,6 +211,15 @@ GetTargetArch(){
 	ExportDESLTarget ${DESL_ARCH_BUILD};
 	export DESL_TARGET=${NEW_DESL_TARGET};
 
+	# Static build
+	[ ! "${ARGS_OPT_LONG_Static}${ARGS_OPT_LONG_s}" = '' ] && {
+		export DESLB_STATIC=1;
+		DESL_TARGET="${DESL_TARGET}_static";
+		DESL_ARCH="${DESL_ARCH}_s";
+	} || {
+		export DESLB_STATIC=0;
+	}
+
 	# Generate 'BUILDER_TARGET' by 'BUILDER_ARCH'
 	ExportDESLTarget ${BUILDER_ARCH_BUILD};
 	export BUILDER_TARGET=${NEW_DESL_TARGET};
@@ -212,7 +231,6 @@ ExportDESLTarget(){
 	local OFS=${IFS};
 	local IFS='-';
 	set -- ${*}
-
 	case "${*}" in
 		*_hf	) NEW_DESL_TARGET="${1%_*}-des-linux_hf";;
 		*_sf	) NEW_DESL_TARGET="${1%_*}-des-linux_sf";;
@@ -232,7 +250,7 @@ ExportDirsPath(){
 	export INCLUDES_DIR="${SCRIPTS_DIR}"/includes;
 
 	export BUILD_DIR="${BUILD_ROOT_DIR}/desl-${DESL_ARCH}";
-	export BUILD_DIR_BOOTSTRAP="${BUILD_ROOT_DIR}/bootstrap-${BOOTSTRAP_ARCH}/builder-${BUILDER_ARCH}";
+	export BUILD_BOOTSTRAP_DIR="${BUILD_ROOT_DIR}/bootstrap-${BOOTSTRAP_ARCH}/builder-${BUILDER_ARCH}";
 	export SHARED_SOURCE_ROOT_DIR="${BUILD_ROOT_DIR}/shared";
 
 	export BOOTSTRAP_BASE_DIR="${BOOTSTRAP_ROOT_PREFIX}-${BOOTSTRAP_ARCH}";
@@ -253,9 +271,9 @@ ExportDirsPath(){
 
 	export IMAGE_DIR="${IMAGE_ROOT_DIR}/desl-${DESL_ARCH}";
 	export DLP_DIR="${IMAGE_DIR}/packages";
-	export DLP_DIR_BUILDER="${IMAGE_ROOT_DIR}/desl-${BUILDER_ARCH}/packages";
-	export DLP_DIR_BASE="${IMAGE_ROOT_DIR}/builder-${BUILDER_ARCH}/base-${BASE_ARCH}/packages"
-	export DLP_DIR_TOOLCHAIN="${IMAGE_ROOT_DIR}/builder-${BUILDER_ARCH}/desl-${DESL_ARCH}/packages"
+	export DLP_BUILDER_DIR="${IMAGE_ROOT_DIR}/desl-${BUILDER_ARCH}/packages";
+	export DLP_BASEARCH_DIR="${IMAGE_ROOT_DIR}/builder-${BUILDER_ARCH}/base-${BASE_ARCH}/packages"
+	export DLP_TOOLCHAIN_DIR="${IMAGE_ROOT_DIR}/builder-${BUILDER_ARCH}/desl-${DESL_ARCH}/packages"
 
 	export IMAGE_BOOTSTRAP_DIR="${IMAGE_ROOT_DIR}/bootstrap-${BOOTSTRAP_ARCH}";
 	export IMAGE_BUILDER_DIR="${IMAGE_ROOT_DIR}/desl-${BUILDER_ARCH}";
@@ -297,12 +315,12 @@ ExportByArgs(){
 
 	[ ! "${ARGS_OPT_LONG_Static}" = '' ] && DESL_FORCE_STATIC=1;
 
-	[ "${ARGS_OPT_LONG_help}" = "-" ] && ARGS_TARGET=help;
-	[ "${ARGS_OPT_LONG_h}" = "-" ] && ARGS_TARGET=help;
-	[ "${ARGS_OPT_SHORT_h}" = "-" ] && ARGS_TARGET=help;
+	[ "${ARGS_OPT_LONG_help}" = "-" ] && ARGS_TARGET_EX='help';
+	[ "${ARGS_OPT_LONG_h}" = "-" ] && ARGS_TARGET_EX='help';
+	[ "${ARGS_OPT_SHORT_h}" = "-" ] && ARGS_TARGET_EX='help';
 
 	# /M: option to override mode
-	[ ! "${ARGS_OPT_LONG_M}" = '' ] && ARGS_TARGET=${ARGS_OPT_LONG_M:1};
+	[ ! "${ARGS_OPT_LONG_M}" = '' ] && ARGS_TARGET_EX="${ARGS_OPT_LONG_M:1}";
 
 	return 0;
 }
@@ -320,7 +338,6 @@ SetupToolchainSharedDir(){
 		warning "Initializing dlpm shared directory."
 		rm -rf "${TOOLCHAIN_USER_BASE_DIR}"
 		rm -rf "${TOOLCHAIN_TOOLS_DIR}"
-		rm -rf "${BOOTSTRAP_DIR}/usr"
 	}
 
 	local DLPI_ARCH_LOCAL="${DESL_ARCH}";
@@ -331,17 +348,17 @@ SetupToolchainSharedDir(){
 		TOOLCHAIN_ARCH_LOCAL="${BUILDER_ARCH_ORG}";
 	}
 
-	[ ! -e "${TOOLCHAIN_DIR}" ] && {
+	[ ! -e "${TOOLCHAIN_DIR}/.dlp/dlp.conf" ] && {
 		mkdir -p "${TOOLCHAIN_DIR}" || return ${?};
 		RunScript "${SCRIPTS_DIR}/dlpi" /Initialize /Root:${TOOLCHAIN_DIR} /Platform:${TOOLCHAIN_ARCH_LOCAL} /System:DESLBuilder || return ${?};
 	}
 
-	[ ! -e "${TOOLCHAIN_USR_DIR}" ] && {
+	[ ! -e "${TOOLCHAIN_USR_DIR}/.dlp/dlp.conf" ] && {
 		mkdir -p "${TOOLCHAIN_USR_DIR}" || return ${?};
 		RunScript "${SCRIPTS_DIR}/dlpi" /Initialize /Root:${TOOLCHAIN_USR_DIR} /Platform:${DLPI_ARCH_LOCAL} ${System} || return ${?};
 	}
 
-	[ ! -e "${TOOLCHAIN_TOOLS_DIR}" ] && {
+	[ ! -e "${TOOLCHAIN_TOOLS_DIR}/.dlp/dlp.conf" ] && {
 		mkdir -p "${TOOLCHAIN_TOOLS_DIR}/bin" || return ${?};
 		RunScript "${SCRIPTS_DIR}/dlpi" /Initialize /Root:${TOOLCHAIN_TOOLS_DIR} /Platform:${BUILDER_ARCH} ${System} || return ${?};
 	}
@@ -375,15 +392,21 @@ VerifyArch(){
 	local a;
 	local OFS=${IFS};
 	local IFS;
-	[ "${SKIP_ARCH_VERIFY}" != '' ] && {
+	local DESL_ARCH_LOCAL="${DESL_ARCH}";
+
+	[ ! "${SKIP_ARCH_VERIFY}" = '' ] && {
 		return 0;
+	}
+
+	[ "${DESLB_STATIC}" = '1' ] && {
+		DESL_ARCH_LOCAL="${DESL_ARCH%_s}";
 	}
 
 	IFS=$'\n\r';
 	for a in `ConfigFileList "${SCRIPTS_DIR}/Arch.lst" Arch`; do
 		case "${a}" in
 			*=*,* )
-				[ "${a%%=*}" = "${DESL_ARCH}" ] && {
+				[ "${a%%=*}" = "${DESL_ARCH_LOCAL}" ] && {
 					export BASE_ARCH_ARGS="${a#*=}";
 					export BASE_ARCH="${BASE_ARCH_ARGS%%,*}";
 					BASE_ARCH="${BASE_ARCH// /}";
@@ -400,7 +423,7 @@ VerifyArch(){
 					ExportDESLTarget ${BASE_ARCH_BUILD};
 					export BASE_TARGET=${NEW_DESL_TARGET};
 
-					export BASE_TOOLCHAIN_DIR="${TOOLCHAIN_ROOT_DIR}/builder-${BUILDER_ARCH}/base-${BASE_ARCH}";
+					export TOOLCHAIN_BASEARCH_DIR="${TOOLCHAIN_ROOT_DIR}/builder-${BUILDER_ARCH}/base-${BASE_ARCH}";
 
 					return 0;
 				}
@@ -429,7 +452,7 @@ ChangeEnvIfPackageIsBootstrap(){
 	DESL_ARCH_BUILD="${BOOTSTRAP_ARCH_ORG}";
 	DESL_ARCH_BUILD_ORG="${BOOTSTRAP_ARCH_ORG}";
 
-	BUILD_DIR=${BUILD_DIR_BOOTSTRAP};
+	BUILD_DIR=${BUILD_BOOTSTRAP_DIR};
 	DLP_DIR=${DLP_BOOTSTRAP_DIR};
 
 	TOOLCHAIN_DIR="${BOOTSTRAP_DIR}";
@@ -451,9 +474,9 @@ ChangeEnvIfPackageIsToolchainBase(){
 			DESL_ARCH_BUILD="${BASE_ARCH_BUILD}";
 
 			BUILD_DIR="${BUILD_ROOT_DIR}/builder-${BUILDER_ARCH}/base-${BASE_ARCH}";
-			DLP_DIR="${DLP_DIR_BASE}";
+			DLP_DIR="${DLP_BASEARCH_DIR}";
 
-			TOOLCHAIN_DIR="${BASE_TOOLCHAIN_DIR}";
+			TOOLCHAIN_DIR="${TOOLCHAIN_BASEARCH_DIR}";
 			TOOLCHAIN_USER_BASE_DIR="${TOOLCHAIN_DIR}";
 			TOOLCHAIN_USR_DIR="${TOOLCHAIN_USER_BASE_DIR}";
 			TOOLCHAIN_LOCAL_DIR="${TOOLCHAIN_USER_BASE_DIR}";
@@ -471,7 +494,7 @@ ChangeEnvIfPackageIsToolchain(){
 	case "${DESL_BUILD_PACKAGE}" in
 		toolchain/* | toolchain )
 			BUILD_DIR="${BUILD_ROOT_DIR}/builder-${BUILDER_ARCH}/desl-${DESL_ARCH}";
-			DLP_DIR="${DLP_DIR_TOOLCHAIN}";
+			DLP_DIR="${DLP_TOOLCHAIN_DIR}";
 
 			INTERNAL_NO_LINK_USR_DIR=1;
 		;;
@@ -492,12 +515,14 @@ CheckPrerequisites(){
 	export DESLB_SKIP_PREREQ=1;
 
 	. ${INCLUDES_DIR}/CheckPrerequisites.sh
-	RunCheckPrerequisites || return ${?};
+	RunCheckPrerequisites || {
+		error "Failed to solve prerequisites"
+		return 1;
+	}
 }
 
 RunMode(){
-
-	case "${ARGS_TARGET}" in
+	case "${ARGS_TARGET_EX}" in
 
 		# Standard options
 		'Build' | '' ) # Prepare,Config,Compile,Install
@@ -621,7 +646,7 @@ RunMode(){
 			return 0;;
 
 		* )
-			error "Unknown mode '${ARGS_TARGET}' specified."
+			error "Unknown mode '${ARGS_TARGET_EX}' specified."
 			warning 'You must specify the mode option in the first argument.'
 			return 127;
 			;;
diff --git a/scripts/dlpm b/scripts/dlpm
--- a/scripts/dlpm
+++ b/scripts/dlpm
@@ -42,6 +42,8 @@ Main(){
 	local CERT_DLP_DIR="${CERT_DIR}/CA/";
 	local CERT_REP_DIR="${CERT_DIR}/repositories/";
 
+	local DLPM_DRY_RUN=0;
+
 	case "${ARGS_TARGET}" in
 		Update )
 			return ${?};;
@@ -125,12 +127,12 @@ EnterSessionEx(){
 	local TMPDIR="/tmp/DLPM_${RANDOM}_${RANDOM}_${RANDOM}_${RANDOM}_${RANDOM}/";
 	mkdir -p "${TMPDIR}" || return ${?};
 
-	info 'Starting DLPM session'
+	# info 'Starting DLPM session'
 
 	"${1}" "${TMPDIR}"
 	local R=${?};
 
-	info "DLPM session exited with status code: ${R}"
+	# info "DLPM session exited with status code: ${R}"
 
 	rm -rf "${TMPDIR}"
 
@@ -141,11 +143,13 @@ DLPMInstall(){
 	local x;
 	local LF=$'\n';
 
+	InitResolveList;
+
 	ResolveFileArgs ${ARGS_FILE_LIST} || return ${?};
 	ResolveDepends || return ${?};
 
-	[ "${DLPM_DRY_RUN:+1}" = '1' ] && {
-		echo "${DLPM_RESOLVED_FILES}"
+	[ "${DLPM_DRY_RUN:-0}" = '1' ] && {
+		echo "${DLPM_LIST_FILES}"
 		return 0;
 	}
 
@@ -163,7 +167,7 @@ DLPMInstall(){
 	local INSTALL_FILES='';
 
 	info 'Downloading packages...'
-	for x in ${DLPM_RESOLVED_FILES}; do
+	for x in ${DLPM_LIST_FILES}; do
 		case "${x}" in
 			file://* ) INSTALL_FILES="${INSTALL_FILES}${LF}${x:7}";;
 			dlpm::file://* ) INSTALL_FILES="${INSTALL_FILES}${LF}${x:13}";;
@@ -244,76 +248,11 @@ DLPMRepository(){
 	return 1;
 }
 
-DLPMMakeDB(){
-	# ID | Version | Revision | Platform | System| Size | FileName
-	local DB="${ARGS_OPT_LONG_Dir}/DESLPackage.db"
-	local S256="${ARGS_OPT_LONG_Dir}/DESLPackage.sha256"
-	echo '[DB]' > "${DB}" || return ${?};
-	echo 'Version	= 1' >> "${DB}" || return ${?};
-	echo '' >> "${DB}" || return ${?};
-
-
-	echo '[Packages]' >> "${DB}" || return ${?};
-
-	[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
-		echo '[SHA256]' > "${S256}" || return ${?};
-	}
-
- 	local x xx y;
-	local ID PF SYS VER REV SIZE DEP FN;
-	for x in `find "${ARGS_OPT_LONG_Dir}" -name "*.dlp"`; do
-		local xx="${x//${ARGS_OPT_LONG_Dir}/}";
-		info "Reading: '${xx}'..."
-
-		cpio -F "${x}" -H newc -i --to-stdout DESLPackage.def > "${TMPDIR}/DESLPackage.def" 2>/dev/null || {
-			warning "Failed to open DESLPackage.def in '${x}'"
-			continue;
-		}
-
-		ConfigLoad "${TMPDIR}/DESLPackage.def" DLPackage > /dev/null || return ${?};
-		ConfigGet ID 'DLPackage::DLPInstaller:ID' '-'
-		ConfigGet PF 'DLPackage::DLPInstaller:Platform' '-'
-		ConfigGet SYS 'DLPackage::DLPInstaller:System' '-'
-		ConfigGet VER 'DLPackage::DESLPackage:Version' '0'
-		ConfigGet REV 'DLPackage::DESLPackage:Revision' '0'
-		ConfigGet SIZE 'DLPackage::Data:Size' '0'
-
-		local Depends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'Depends'`;
-		local RuntimeDepends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'RuntimeDepends'`;
-		local DEP='';
-		for y in ${Depends} ${RuntimeDepends}; do
-			DEP="${DEP:+${DEP},}${y}";
-		done
-
-		[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
-			info " Calculating SHA256..."
-			local SHA256=`cat ${x} | sha256sum`;
-			set -- ${SHA256}
-			SHA256="${1}";
-			echo "${xx##/}|${SHA256}" >> "${S256}" || return ${?};
-		}
-
-		echo "${ID}|${PF}|${SYS}|${VER}|${REV}|${SIZE}|${DEP}|${xx##/}" >> "${DB}" || return ${?};
-	done
-
-	[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
-		info " Calculating SHA256 of Database..."
-		local SHA256=`cat ${DB} | sha256sum`;
-		set -- ${SHA256}
-		SHA256="${1}";
-		echo "DESLPackage.db|${SHA256}" >> "${S256}" || return ${?};
-	}
-
-
-	cat "${DB}"
-	cat "${S256}"
-	return 0;
-}
-
 InitResolveList(){
 	# Return val: NOT local.
-	DLPM_RESOLVED_FILES='';
-	DLPM_DEPENDS_LIST='';
+	DLPM_LIST_ID='';
+	DLPM_LIST_FILES='';
+
 	DLPM_DEPENDS_SIZE=0;
 
 	for x in `set | grep DLPM__DEP_`; do
@@ -327,19 +266,10 @@ AddResolveListFromFile(){ # PackagePath # ENV: DLPM_NO_SOLVE_DEPENDS
 	local LF=$'\n';
 	local y ID PF SYS SIZE;
 
-	[ ! -e "${x}" ] && {
-		error "File '${x}' is not found."
-		return 1;
-	}
-
-	x=`readlink -f "${x}" 2>/dev/null || echo "${x}"`;
-
-	DLPM_RESOLVED_FILES="${DLPM_RESOLVED_FILES}${LF}file://${x}";
-
 	[ "${DLPM_NO_SOLVE_DEPENDS}" = '1' ] && return 0;
 
 	cpio -F "${x}" -H newc -i --to-stdout DESLPackage.def > "${TMPDIR}/DESLPackage.def" 2>/dev/null || {
-		error "Failed to open DESLPackage.def in '${x}'"
+		error "Invalid DLP file: Failed to open DESLPackage.def in '${x}'"
 		return 1;
 	}
 
@@ -356,6 +286,7 @@ AddResolveListFromFile(){ # PackagePath # ENV: DLPM_NO_SOLVE_DEPENDS
 
 	local Depends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'Depends'`;
 	local RuntimeDepends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'RuntimeDepends'`;
+
 	for y in ${Depends} ${RuntimeDepends}; do
 		AddDependsList "${y}"
 	done
@@ -377,7 +308,7 @@ AddDependsList(){ # ID to add
 
 	eval R="\${DLPM__DEP_ID_ADDED_${IDX}}";
 	[ ! "${R}" = '1' ] && {
-		DLPM_DEPENDS_LIST="${DLPM_DEPENDS_LIST:+${DLPM_DEPENDS_LIST}${LF}}${ID}";
+		DLPM_LIST_ID="${DLPM_LIST_ID:+${DLPM_LIST_ID}${LF}}${ID}";
 		eval DLPM__DEP_ID_ADDED_${IDX}=1;
 		return 0;
 	}
@@ -385,9 +316,30 @@ AddDependsList(){ # ID to add
 	return 1;
 }
 
-ResolveFileArgs(){
-	InitResolveList;
+AddDLPFileList(){
+	local x="${1}";
+	local LF=$'\n';
 
+	x=`readlink -f "${x}" 2>/dev/null || echo "${x}"`;
+
+	[ ! -e "${x}" ] && {
+		error "File '${x}' is not found."
+		return 1;
+	}
+
+	DLPM_LIST_FILES="${DLPM_LIST_FILES:+${DLPM_LIST_FILES}}${LF}file://${x}";
+
+	return 0;
+}
+
+AddDLPIDList(){
+	local x="${1}";
+	local LF=$'\n';
+	DLPM_LIST_ID="${DLPM_LIST_ID:+${DLPM_LIST_ID}}${LF}${x}";
+	return 0;
+}
+
+ResolveFileArgs(){ # Normalize DLP path if location of DLP is specified
 	local x;
 
 	for x in "${@}"; do
@@ -399,12 +351,12 @@ ResolveFileArgs(){
 					error 'Failed to download '${x}' .'
 					return 1;
 				}
-				AddResolveListFromFile "${x}" || return ${?};
+				AddDLPFileList "${F}" || return ${?};
 			;;
 
 			file://* )
 				x="${x:7}";
-				AddResolveListFromFile "${x}" || return ${?};
+				AddDLPFileList "${x}" || return ${?};
 			;;
 
 			*://* )
@@ -413,16 +365,16 @@ ResolveFileArgs(){
 			;;
 
 			./* | ../* | /*/* | ~/* | *.* )
-				AddResolveListFromFile "${x}" || return ${?};
+				AddDLPFileList "${x}" || return ${?};
 			;;
 
 			*/* | * )
 				[ -e "${x}" ] && {
-					AddResolveListFromFile "${x}" || return ${?};
+					AddDLPFileList "${x}" || return ${?};
 					continue;
 				}
 
-				AddDependsList "${x}"
+				AddDLPIDList "${x}"
 
 				continue;
 			;;
@@ -439,6 +391,11 @@ ResolveDepends(){
 	local DepAdded=1;
 	local RPass=0;
 
+	# Resolve file first
+	for x in ${DLPM_LIST_FILES}; do
+		AddResolveListFromFile "${x:7}" || return ${?};
+	done
+
 	while [ "${DepAdded:-0}" = '1' ]; do
 		RPass=$((RPass+1));
 		[ "$((RPass))" = '64' ] && {
@@ -447,40 +404,40 @@ ResolveDepends(){
 		}
 
 		DepAdded=0;
-		local DEPLIST="${DLPM_DEPENDS_LIST}";
-		DLPM_DEPENDS_LIST='';
+		local DEPLIST="${DLPM_LIST_ID}";
+		DLPM_LIST_ID='';
 
 		for x in ${DEPLIST}; do
-			FindLocal "${x}" && { # Already resolved by local packages
+
+			FindAlready "${x}" && { # Already resolved by location specified DLPs
 				continue;
 			}
 
-			FindDESLBuilder "${x}" && {
-				DLPM_RESOLVED_FILES="${DLPM_RESOLVED_FILES}${LF}file://${DESLBDLP_FILE}";
-				continue;
-			}
-
-			FindDB "${x}" || {
-				[ "${ARGS_OPT_LONG_IgnoreDepends}" = '' ] && {
-					[ "${ARGS_OPT_LONG_Quiet:-0}" = '0' ] && error "Package '${x}' not found."
-					return 1;
-				}
-
-				warning "Package '${x}' not found."
-				continue;
-			}
-
-			IDX="${x//\//_____}";
-			IDX="${IDX//-/___}";
-
-			eval DLPM__DEP_ID_LOCAL_RESOLVED_${IDX}=1;
-			DLPM_RESOLVED_FILES="${DLPM_RESOLVED_FILES}${LF}dlpm::${DBFOUND_FILE}";
-			DLPM_DEPENDS_SIZE=$((DLPM_DEPENDS_SIZE+DBFOUND_SIZE));
-
-			for y in ${DBFOUND_DEPENDS}; do
-				AddDependsList "${y}"
+			FindDESLBuilder "${x}" && { # /DLPDir
+				AddResolveListFromFile "${DESLBDLP_FILE}" || return ${?};
+				DLPM_LIST_FILES="${DLPM_LIST_FILES:+${DLPM_LIST_FILES}${LF}}file://${DESLBDLP_FILE}";
 				DepAdded=1;
-			done
+				continue;
+			}
+
+			FindDB "${x}" && {
+				DLPM_LIST_FILES="${DLPM_LIST_FILES:+${DLPM_LIST_FILES}${LF}}${DBFOUND_FILE}";
+				DLPM_DEPENDS_SIZE=$((DBFOUND_SIZE+DLPM_DEPENDS_SIZE));
+
+				for y in ${DBFOUND_DEPENDS}; do
+					DLPM_LIST_ID="${y}";
+					DepAdded=1;
+				done
+				continue;
+			}
+
+			[ "${ARGS_OPT_LONG_IgnoreDepends}" = '' ] && {
+				[ "${ARGS_OPT_LONG_Quiet:-0}" = '0' ] && error "Package '${x}' is not found."
+				return 1;
+			}
+
+			warning "Package '${x}' is not found."
+			continue;
 		done
 
 	done
@@ -488,7 +445,7 @@ ResolveDepends(){
 	return 0;
 }
 
-FindLocal(){
+FindAlready(){
 	local R IDX;
 	local ID="${1}";
 
@@ -523,7 +480,7 @@ FindDB(){ # 1 ID
 		DLPM_FINDDB_INIT=1
 	}
 
-	local x y P DB;
+	local x y N P DB;
 	for x in `ConfigListWithValue DLPMReps::Repositories`; do
 		N="${x%%=*}";
 		P="${x#*=}";
@@ -580,7 +537,7 @@ FindDESLBuilder(){
 	local DLP_DIR_LOCAL="${ARGS_OPT_LONG_DLPDir:-${DLP_DIR:--}}";
 
 	[ "${DLP_DIR_LOCAL:--}" = '-' ] && {
-		return 0;
+		return 1;
 	}
 
 	# Not local
@@ -596,6 +553,72 @@ FindDESLBuilder(){
 	done
 
 	return 1;
+}
+
+DLPMMakeDB(){
+	# ID | Version | Revision | Platform | System| Size | FileName
+	local DB="${ARGS_OPT_LONG_Dir}/DESLPackage.db"
+	local S256="${ARGS_OPT_LONG_Dir}/DESLPackage.sha256"
+	echo '[DB]' > "${DB}" || return ${?};
+	echo 'Version	= 1' >> "${DB}" || return ${?};
+	echo '' >> "${DB}" || return ${?};
+
+
+	echo '[Packages]' >> "${DB}" || return ${?};
+
+	[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
+		echo '[SHA256]' > "${S256}" || return ${?};
+	}
+
+ 	local x xx y;
+	local ID PF SYS VER REV SIZE DEP FN SHA256;
+	for x in `find "${ARGS_OPT_LONG_Dir}" -name "*.dlp"`; do
+		local xx="${x//${ARGS_OPT_LONG_Dir}/}";
+		info "Reading: '${xx}'..."
+
+		cpio -F "${x}" -H newc -i --to-stdout DESLPackage.def > "${TMPDIR}/DESLPackage.def" 2>/dev/null || {
+			warning "Failed to open DESLPackage.def in '${x}'"
+			continue;
+		}
+
+		ConfigLoad "${TMPDIR}/DESLPackage.def" DLPackage > /dev/null || return ${?};
+		ConfigGet ID 'DLPackage::DLPInstaller:ID' '-'
+		ConfigGet PF 'DLPackage::DLPInstaller:Platform' '-'
+		ConfigGet SYS 'DLPackage::DLPInstaller:System' '-'
+		ConfigGet VER 'DLPackage::DESLPackage:Version' '0'
+		ConfigGet REV 'DLPackage::DESLPackage:Revision' '0'
+		ConfigGet SIZE 'DLPackage::Data:Size' '0'
+
+		local Depends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'Depends'`;
+		local RuntimeDepends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'RuntimeDepends'`;
+		local DEP='';
+		for y in ${Depends} ${RuntimeDepends}; do
+			DEP="${DEP:+${DEP},}${y}";
+		done
+
+		[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
+			info " Calculating SHA256..."
+			SHA256=`cat ${x} | sha256sum`;
+			set -- ${SHA256}
+			SHA256="${1}";
+			echo "${xx##/}|${SHA256}" >> "${S256}" || return ${?};
+		}
+
+		echo "${ID}|${PF}|${SYS}|${VER}|${REV}|${SIZE}|${DEP}|${xx##/}" >> "${DB}" || return ${?};
+	done
+
+	cat "${DB}"
+
+	[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
+		info " Calculating SHA256 of Database..."
+		SHA256=`cat ${DB} | sha256sum`;
+		set -- ${SHA256}
+		SHA256="${1}";
+		echo "DESLPackage.db|${SHA256}" >> "${S256}" || return ${?};
+		cat "${S256}"
+	}
+
+	return 0;
 }
 
 error(){
