dlpi / dlpm: dlpm resolver

diff --git a/scripts/dlpi b/scripts/dlpi
--- a/scripts/dlpi
+++ b/scripts/dlpi
@@ -13,22 +13,33 @@ Main(){
 	. ${sRoot}/ArgsParser.sh
 	. ${sRoot}/ConfigManager.sh
 
-
 	ParseArgs "${@}";
+
+	local ROOT_DIR="${ARGS_OPT_LONG_Root:-/usr}/";
+	local DLPI_DIR="${ROOT_DIR}/.dlp/";
+
 	case "${ARGS_TARGET}" in
 		Install )
 			EnterSession DLPIInstall;
 			return ${?};;
-		Check ) ;;
+		Check )
+			EnterSession DLPICheck;
+			return ${?};;
+
 		Remove | Uninstall )
 			EnterSession DLPIRemove;
 			return ${?};;
-		List) ;;
+		List)
+			EnterSession DLPIList;
+			return ${?};;
 		Extract )
 			EnterSession DLPIExtract;
 			return ${?};;
 		Initialize )
 			EnterSession DLPIInitialize;
+			return ${?};;
+		Cleanup )
+			EnterSession DLPICleanup;
 			return ${?};;
 		Create )
 			EnterSession DLPICreate;
@@ -44,25 +55,26 @@ EnterSession(){
 	mkdir -p "${TMPDIR}" || return ${?};
 
 	info 'Starting DLPI session'
+
 	"${1}" "${TMPDIR}"
 	local R=${?};
+
 	info "DLPI session exited with status code: ${R}"
 
 	rm -rf "${TMPDIR}" || return ${?};
 	return ${R};
 }
 
-# /List /Installed or /File:<DLP>
-# /Check /Installed or /File:
+DLPIInstall(){ # /Install /File:<DLP Path> [/Root:<DLP Root>]
+		# [/SkipVerify] [/Force]
+		# [/IgnorePlatform] [/IgnoreSystem] [/IgnoreDepends] [/IgnoreConflict] [/IgnoreFreeSpace]
+	DLPICleanup
 
-DLPIInstall(){ # /Install /File:<DLP Path> [/Root:<DLP Root>] [/Force] [/IgnorePlatform] [/IgnoreSystem] [/IgnoreDepends] [/IgnoreConflict]
 	[ ! "${ARGS_OPT_LONG_File+1}" = '1' ] && {
 		DLPIUsage
 		return 1;
 	}
 
-	local ROOT_DIR="${ARGS_OPT_LONG_Root:-/usr}/";
-	local DLPI_DIR="${ROOT_DIR}/.dlpi/";
 	local DLP_CONFIG="${DLPI_DIR}/dlp.conf";
 	[ ! -e "${DLP_CONFIG}" ] && {
 		error "Directory '${ROOT_DIR}' is not initialized with dlpi."
@@ -89,26 +101,39 @@ DLPIInstall(){ # /Install /File:<DLP Path> [/Root:<DLP Root>] [/Force] [/IgnoreP
 
 
 	[ -e "${DLPI_DIR}/installed/${ID//\//_____}.dlpi" ] && {
+		[ "${ARGS_OPT_LONG_Force:+1}" = '1' ] && return 0;
+
 		error "Package '${ID}' is already installed."
 		return 1;
 	}
 
-	[ "${ARGS_OPT_LONG_Force}${ARGS_OPT_LONG_IgnorePlatform}" = '' ] && {
+	[ "${ARGS_OPT_LONG_IgnorePlatform}" = '' ] && {
 		[ ! "${Platform_Root}" = "${Platform_Package}" ] && {
 			error "Package platform '${Platform_Package}' is not for this system '${Platform_Root}'";
 			return 2;
 		}
 	}
-	[ "${ARGS_OPT_LONG_Force}${ARGS_OPT_LONG_IgnoreSystem}" = '' ] && {
+	[ "${ARGS_OPT_LONG_IgnoreSystem}" = '' ] && {
 		[ ! "${BaseSystem_Root}" = "${BaseSystem_Pacakge}" ] && {
 			error "Package target system '${BaseSystem_Pacakge}' is not for this system '${BaseSystem_Root}'";
 			return 2;
 		}
 	}
 
-	[ "${ARGS_OPT_LONG_Force}${ARGS_OPT_LONG_IgnoreDepends}" = '' ] && {
+	[ "${ARGS_OPT_LONG_IgnoreFreeSpace}" = '' ] && {
+		local Free Size;
+		ConfigGet Size 'DLPackage::Data:Size' 0
+		set -- `df -m "${ROOT_DIR}"`
+		Free="${11}";
+		local Remain="$((Free-(Size/1048576)))";
+		[ "${Remain:0:1}" = '-' ] && {
+			error "Not enough space on '${ROOT_DIR}'. (Required = $((Size/1048576)) MB, Free = ${Free} MB)"
+			return 3;
+		}
+	}
+
+	[ "${ARGS_OPT_LONG_IgnoreDepends}" = '' ] && {
 		info 'Checking dependency...'
-		local Depends RuntimeDepends;
 		local Depends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'Depends'`;
 		local RuntimeDepends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'RuntimeDepends'`;
 		CheckDepends "${DLPI_DIR}" "${Depends} ${RuntimeDepends}" || return ${?};
@@ -116,6 +141,25 @@ DLPIInstall(){ # /Install /File:<DLP Path> [/Root:<DLP Root>] [/Force] [/IgnoreP
 
 	info 'Loading file list...'
 	local FILE_LIST=`DLPI_LIST_ONLY=1 DLPIExtract`;
+
+	[ "${ARGS_OPT_LONG_IgnoreConflict}" = '' ] && {
+		info 'Checking installed files...'
+		local x;
+		local ERR=0;
+		for x in ${FILE_LIST}; do
+			[ ! -d "${ROOT_DIR}/${x}" ] && {
+				[ -e "${ROOT_DIR}/${x}" ] && {
+					error "Conflict: '${x}'"
+					ERR=1;
+				}
+			}
+		done
+		[ "${ERR}" = '1' ] && {
+			error 'Some files are conflicted with other packages	'
+			error '/IgnoreConflict to skip this check and will overwrite files.'
+			return 1;
+		}
+	}
 
 	info 'Installing...'
 	mkdir -p "${DLPI_DIR}/installed/" || return ${?};
@@ -125,19 +169,33 @@ DLPIInstall(){ # /Install /File:<DLP Path> [/Root:<DLP Root>] [/Force] [/IgnoreP
 
 	ARGS_OPT_LONG_Dir="${ROOT_DIR}" ARGS_OPT_LONG_Verbose=1 DLPIExtract || return ${?};
 
+	sync
+
+	[ "${ARGS_OPT_LONG_SkipVerify}" = '' ] && {
+		info 'Checking files...'
+		local x;
+		for x in ${FILE_LIST}; do
+			[ ! -e "${ROOT_DIR}/${x}" ] && {
+				error "File '${x}' is not installed correctly."
+				DLPICleanup
+				return 1;
+			}
+		done
+	}
+
 	mv "${DLPI_DIR}/installed/session.dlpi" "${DLPI_DIR}/installed/${ID//\//_____}.dlpi" || return ${?};
 
 	return 0;
 }
 
-DLPIRemove(){ # /Remove /ID:<DLP ID> [/Root:<DLP Root>]
+DLPIRemove(){ # /Remove /ID:<DLP ID> [/Root:<DLP Root>] [/Force]
+	NOCLEANUP=1 DLPICleanup
+
 	[ ! "${ARGS_OPT_LONG_ID+1}" = '1' ] && {
 		DLPIUsage
 		return 1;
 	}
 
-	local ROOT_DIR="${ARGS_OPT_LONG_Root:-/usr}/";
-	local DLPI_DIR="${ROOT_DIR}/.dlpi/";
 	local DLP_CONFIG="${DLPI_DIR}/dlp.conf";
 	[ ! -e "${DLP_CONFIG}" ] && {
 		error "Directory '${ROOT_DIR}' is not initialized with dlpi."
@@ -147,6 +205,7 @@ DLPIRemove(){ # /Remove /ID:<DLP ID> [/Root:<DLP Root>]
 	local ID="${ARGS_OPT_LONG_ID}";
 	local DLPI_FILE="${DLPI_DIR}/installed/${ID//\//_____}.dlpi";
 	[ ! -e "${DLPI_FILE}" ] && {
+		[ "${ARGS_OPT_LONG_Force:+1}" = '1' ] && return 0;
 		error "Package '${ID}' is not installed."
 		return 1;
 	}
@@ -189,8 +248,8 @@ DLPIInitialize(){ # /Initialize /Root:<DLP Root> /Platform:<Arch> [/System:<Syst
 		return 1;
 	}
 
-	local DLP_CONFIG="${ARGS_OPT_LONG_Root}/.dlpi/dlp.conf";
-	mkdir -p "${ARGS_OPT_LONG_Root}/.dlpi"
+	local DLP_CONFIG="${ARGS_OPT_LONG_Root}/.dlp/dlp.conf";
+	mkdir -p "${ARGS_OPT_LONG_Root}/.dlp"
 	echo '[DLP]' > "${DLP_CONFIG}"
 	echo "Platform	= ${ARGS_OPT_LONG_Platform}" >> "${DLP_CONFIG}"
 	echo "System	= ${ARGS_OPT_LONG_System:-DESLinux}" >> "${DLP_CONFIG}"
@@ -263,6 +322,82 @@ DLPIExtract(){ # /Extract /File:<DLP Path> [/Dir:<Extract to>]  [/Verbose, /v] [
 	return ${?};
 }
 
+DLPIList(){ # /List /Installed or /File:<DLP>
+	[ "${ARGS_OPT_LONG_File:+1}" ] && {
+		DLPI_LIST_ONLY=1 DLPIExtract;
+		return ${?};
+	}
+
+	[ "${ARGS_OPT_LONG_Installed:+1}" ] && {
+		DLPIList_Installed;
+		return ${?};
+	}
+
+	DLPI_List_Installed
+	return ${?};
+}
+
+DLPIList_Installed(){
+	local DLP_CONFIG="${DLPI_DIR}/dlp.conf";
+	[ ! -e "${DLP_CONFIG}" ] && {
+		error "Directory '${ROOT_DIR}' is not initialized with dlpi."
+		return 1;
+	}
+
+	local x;
+	for x in ${DLPI_DIR}/installed/*.dlpi; do
+		x="${x//${DLPI_DIR}\/installed\//}";
+		x="${x//_____/\/}";
+		echo "${x%.dlpi}"
+	done
+	return 0;
+}
+
+DLPICheck(){ # /Check /Installed or /File:<DLP>
+	[ "${ARGS_OPT_LONG_ID:-0}:${ARGS_OPT_LONG_File+1}" = '0:1' ] && {
+		DLPIGetIDFromDLP || return ${?};
+	}
+
+	[ ! "${ARGS_OPT_LONG_ID+1}" = '1' ] && {
+		DLPIUsage
+		return 2;
+	}
+
+	local DLP_CONFIG="${DLPI_DIR}/dlp.conf";
+	[ ! -e "${DLP_CONFIG}" ] && {
+		error "Directory '${ROOT_DIR}' is not initialized with dlpi."
+		return 2;
+	}
+
+	local ID="${ARGS_OPT_LONG_ID}";
+	local DLPI_FILE="${DLPI_DIR}/installed/${ID//\//_____}.dlpi";
+	[ ! -e "${DLPI_FILE}" ] && {
+		info "Package '${ID}' is not installed."
+		return 1;
+	}
+	info "Package '${ID}' is already installed."
+	return 0;
+}
+
+DLPICleanup(){
+	[ "${NOCLEANUP:+1}" = '1' ] && return 0;
+	[ ! -e "${DLPI_DIR}/installed/session.dlpi" ] && return 0;
+
+	warning Cleaning up previous session...
+
+	ARGS_OPT_LONG_ID='session' DLPIRemove
+
+	return 0;
+}
+
+DLPIGetIDFromDLP(){
+	cpio -F "${ARGS_OPT_LONG_File}" -H newc -i --to-stdout DESLPackage.def > "${TMPDIR}/DESLPackage.def" 2>/dev/null || return ${?};
+	ConfigLoad "${TMPDIR}/DESLPackage.def" DLPackage > /dev/null || return ${?};
+	local ID ;
+	ConfigGet ID 'DLPackage::DLPInstaller:ID'
+	ARGS_OPT_LONG_ID="${ID}";
+	return 0;
+}
 
 DLPICreate(){ # /Craete /Dir:<Root> /PackageDef:<DESLPackage.def> /Platform:<Arch> /ID:<ID> /SaveTo:<dlp>
 		# [/System:<SystemName>] [/Archive:<type>] [/Compress:<type>] [Type:<arc.comp>]
@@ -295,8 +430,7 @@ DLPICreate(){ # /Craete /Dir:<Root> /PackageDef:<DESLPackage.def> /Platform:<Arc
 	TypeA="${ARGS_OPT_LONG_Archive:-${TypeA:-dla}}";
 	TypeC="${ARGS_OPT_LONG_Compress:-${TypeC:-gz}}";
 
-	local CompApp;
-	local DLP_DATAFILE;
+	local CompApp DLP_DATAFILE;
 	case "${TypeC}" in
 		'' | '-' | 'none' ) TypeC='-'; CompApp='cat'; DLP_DATAFILE='';;
 		'gz' | 'gzip' ) TypeC='gz'; CompApp='gzip'; DLP_DATAFILE='.gz';;
@@ -305,6 +439,10 @@ DLPICreate(){ # /Craete /Dir:<Root> /PackageDef:<DESLPackage.def> /Platform:<Arc
 			error "Unsupported compression type '${TypeC}' specified."
 			return 1;;
 	esac
+
+	set -- `du -bs "${ARGS_OPT_LONG_Dir}"`
+	local Size="${1}";
+	Size=$((Size));
 
 	info 'Creating install archive...'
 	case "${TypeA}" in
@@ -358,6 +496,7 @@ AddDESLPackageDef(){ # Base.def
 	echo '[Data]'
 	echo "Archive	= ${TypeA}"
 	echo "Compress	= ${TypeC}"
+	echo "Size	= ${Size}"
 	echo ''
 	return 0;
 }
diff --git a/scripts/dlpm b/scripts/dlpm
--- a/scripts/dlpm
+++ b/scripts/dlpm
@@ -3,7 +3,386 @@
 Main(){
 	CheckEnv || return ${?};
 
-	warning DLPM
+	# Private: variables
+	local SELF="${BASH_SOURCE:-${DESLB_SELF_PATH:-${0}}}";
+	SELF=`readlink -f "${SELF}" || echo "${SELF}"`;
+
+	local sRoot="${SELF%/*}";
+	local sName="${SELF##*/}";
+	local DLPI="${sRoot}/dlpi";
+
+	. ${sRoot}/ArgsParser.sh
+	. ${sRoot}/ConfigManager.sh
+
+	ParseArgs "${@}";
+
+	local ROOT_DIR="${ARGS_OPT_LONG_Root:-/usr}/";
+	local DLPI_DIR="${ROOT_DIR}/.dlp/";
+	local DLP_CONFIG="${DLPI_DIR}/dlp.conf";
+	local REP_LIST="${DLPI_DIR}/dlpm.lst";
+	local CERT_DIR="${DLPI_DIR}/certificates/";
+	local CERT_DLP_DIR="${CERT_DIR}/CA/";
+	local CERT_REP_DIR="${CERT_DIR}/repositories/";
+
+	case "${ARGS_TARGET}" in
+		Update )
+			return ${?};;
+
+		Repository )
+			EnterSession DLPMRepository;
+			return ${?};;
+
+		Install )
+			EnterSession DLPMInstall;
+			return ${?};;
+
+		Remove | Uninstall )
+			EnterSession DLPMRemove;
+			return ${?};;
+
+		Reinstall )
+			return ${?};;
+
+		List)
+			EnterSession DLPMList;
+			return ${?};;
+
+		Search )
+			return ${?};;
+
+		MakeDB )
+			EnterSessionEx DLPMMakeDB;
+			return ${?};;
+
+		*)
+			DLPMUsage;
+			return 0;;
+	esac
+}
+
+EnterSession(){
+	[ ! -e "${DLP_CONFIG}" ] && {
+		error $DLP_CONFIG
+		error "Directory '${ROOT_DIR}' is not initialized with dlpi."
+		return 1;
+	}
+	[ ! -e "${REP_LIST}" ] && {
+		touch "${REP_LIST}" || return ${?};
+	}
+	[ ! -e "${CERT_DLP_DIR}" ] && {
+		mkdir -p "${CERT_DLP_DIR}" || return ${?};
+	}
+	[ ! -e "${CERT_REP_DIR}" ] && {
+		mkdir -p "${CERT_REP_DIR}" || return ${?};
+	}
+
+	EnterSessionEx "${@}"
+	return ${?};
+}
+
+EnterSessionEx(){
+	local TMPDIR="/tmp/DLPM_${RANDOM}_${RANDOM}_${RANDOM}_${RANDOM}_${RANDOM}/";
+	mkdir -p "${TMPDIR}" || return ${?};
+
+	info 'Starting DLPM session'
+
+	"${1}" "${TMPDIR}"
+	local R=${?};
+
+	info "DLPM session exited with status code: ${R}"
+
+	rm -rf "${TMPDIR}" || return ${?};
+
+}
+
+DLPMInstall(){
+	ResolveIDList ${ARGS_FILE_LIST}
+}
+
+DLPMRepository(){
+	ConfigLoad "${REP_LIST}" DLPMReps > /dev/null || return ${?};
+
+	case "${ARGS_OPT_LONG_Add:+/A}${ARGS_OPT_LONG_Remove:+/R}${ARGS_OPT_LONG_List:+/L}" in
+		/L | '' )
+			ConfigListWithValue 'DLPMReps::Repositories'
+			return 0;
+		;;
+
+		/A )
+			[ ! "${ARGS_OPT_LONG_Name:+1}:${ARGS_OPT_LONG_URL:+1}" = '1:1' ] && {
+				DLPMUsage Repository;
+				return 1;
+			}
+
+			[ "${ARGS_OPT_LONG_Force:-0}" = '0' ] && {
+				local x;
+				ConfigGet x "DLPMReps::Repositories:${ARGS_OPT_LONG_Name}" ''
+				[ ! "${x}" = '' ] && {
+					error "Repository '${ARGS_OPT_LONG_Name}' is already added."
+					return 1;
+				}
+			}
+			ConfigSet "DLPMReps::Repositories:${ARGS_OPT_LONG_Name}" "${ARGS_OPT_LONG_URL}"
+
+			ConfigSave "${REP_LIST}" DLPMReps || return ${?};
+			return 0;
+		;;
+
+		/R )
+			[ ! "${ARGS_OPT_LONG_Name:+1}" = '1' ] && {
+				DLPMUsage Repository;
+				return 1;
+			}
+
+			[ "${ARGS_OPT_LONG_Force:-0}" = '0' ] && {
+				local x;
+				ConfigGet x "DLPMReps::Repositories:${ARGS_OPT_LONG_Name}" ''
+				[ "${x}" = '' ] && {
+					error "Repository '${ARGS_OPT_LONG_Name}' is not exist."
+					return 1;
+				}
+			}
+			ConfigDelete "DLPMReps::Repositories:${ARGS_OPT_LONG_Name}"
+			rm -f "${CERT_REP_DIR}/${ARGS_OPT_LONG_Name}.cer"
+
+			ConfigSave "${REP_LIST}" DLPMReps || return ${?};
+			return 0;
+		;;
+
+		* )
+			DLPMUsage;
+			return 1;
+		;;
+	esac
+
+	return 1;
+}
+
+DLPMMakeDB(){
+	# ID | Version | Revision | Platform | System| Size | FileName
+	local DB="${ARGS_OPT_LONG_Dir}/DESLPackage.db"
+	local S256="${ARGS_OPT_LONG_Dir}/DESLPackage.sha256"
+	echo '[DB]' > "${DB}" || return ${?};
+	echo 'Version	= 1' >> "${DB}" || return ${?};
+	echo '' >> "${DB}" || return ${?};
+
+
+	echo '[Packages]' >> "${DB}" || return ${?};
+
+	[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
+		echo '[SHA256]' > "${S256}" || return ${?};
+	}
+
+ 	local x xx y;
+	local ID PF SYS VER REV SIZE DEP FN;
+	for x in `find "${ARGS_OPT_LONG_Dir}" -name "*.dlp"`; do
+		local xx="${x//${ARGS_OPT_LONG_Dir}/}";
+		info "Reading: '${xx}'..."
+
+		cpio -F "${x}" -H newc -i --to-stdout DESLPackage.def > "${TMPDIR}/DESLPackage.def" 2>/dev/null || {
+			warning "Failed to open DESLPackage.def in '${x}'"
+			continue;
+		}
+
+		ConfigLoad "${TMPDIR}/DESLPackage.def" DLPackage > /dev/null || return ${?};
+		ConfigGet ID 'DLPackage::DLPInstaller:ID' '-'
+		ConfigGet PF 'DLPackage::DLPInstaller:Platform' '-'
+		ConfigGet SYS 'DLPackage::DLPInstaller:System' '-'
+		ConfigGet VER 'DLPackage::DESLPackage:Version' '0'
+		ConfigGet REV 'DLPackage::DESLPackage:Revision' '0'
+		ConfigGet SIZE 'DLPackage::Data:Size' '0'
+
+		local Depends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'Depends'`;
+		local RuntimeDepends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'RuntimeDepends'`;
+		local DEP='';
+		for y in ${Depends} ${RuntimeDepends}; do
+			DEP="${DEP:+${DEP},}${y}";
+		done
+
+		[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
+			info " Calculating SHA256..."
+			local SHA256=`cat ${x} | sha256sum`;
+			set -- ${SHA256}
+			SHA256="${1}";
+			echo "${xx##/}|${SHA256}" >> "${S256}" || return ${?};
+		}
+
+		echo "${ID}|${PF}|${SYS}|${VER}|${REV}|${SIZE}|${DEP}|${xx##/}" >> "${DB}" || return ${?};
+	done
+
+	[ "${ARGS_OPT_LONG_SHA256:+1}" = '1' ] && {
+		info " Calculating SHA256 of Database..."
+		local SHA256=`cat ${DB} | sha256sum`;
+		set -- ${SHA256}
+		SHA256="${1}";
+		echo "DESLPackage.db|${SHA256}" >> "${S256}" || return ${?};
+	}
+
+
+	cat "${DB}"
+	cat "${S256}"
+	return 0;
+}
+
+InitResolveList(){
+	# Return val: NOT local.
+	DLPM_RESOLVED_FILE='';
+	DLPM_RESOLVED_DEPENDS='';
+
+	for x in `set | grep DLPM__DEP_`; do
+		unset ${x}
+	done
+	return 0;
+}
+
+AddResolveListFromFile(){ # PackagePath
+	local x="${1}";
+	local LR=$'\n';
+	local y yy ID R;
+
+	[ ! -e "${x}" ] && {
+		error "File '${x}' is not found."
+		return 1;
+	}
+
+	DLPM_RESOLVED_FILE="${DLPM_RESOLVED_FILE}${LR}file://${1}";
+
+	[ "${DLPM_NO_SOLVE_DEPENDS}" = '1' ] && return 0;
+	cpio -F "${x}" -H newc -i --to-stdout DESLPackage.def > "${TMPDIR}/DESLPackage.def" 2>/dev/null || {
+		error "Failed to open DESLPackage.def in '${x}'"
+		return 1;
+	}
+
+	ConfigLoad "${TMPDIR}/DESLPackage.def" DLPackage > /dev/null || return ${?};
+	ConfigGet ID DLPackage::DLPInstaller:ID
+	ID="${ID//\//_____}";
+	ID="${ID//-/___}";
+
+	local Depends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'Depends'`;
+	local RuntimeDepends=`ConfigFileList "${TMPDIR}/DESLPackage.def" 'RuntimeDepends'`;
+	for y in ${Depends} ${RuntimeDepends}; do
+		yy="${y//\//_____}";
+		yy="${yy//-/___}";
+
+		eval R="\${DLPM__DEP_ID_ADDED_${yy}}";
+		[ ! "${R}" = '1' ] && {
+			DLPM_RESOLVED_DEPENDS="${DLPM_RESOLVED_DEPENDS:+${DLPM_RESOLVED_DEPENDS}${LR}}${y}";
+			eval DLPM__DEP_ID_ADDED_${yy}=1;
+		}
+	done
+
+	eval DLPM__DEP_ID_SOLVED_${ID}=1;
+
+	return 0;
+}
+
+ResolveIDList(){ # ENV:DLPM_NO_SOLVE_DEPENDS=1
+	InitResolveList;
+
+	local x;
+
+	for x in "${@}"; do
+		case ${x} in
+			http://* | https://* | ftp://* )
+				local F="/tmp/remote_${RANDOM}_${RANDOM}_${RANDOM}_${RANDOM}_${RANDOM}.dlp";
+
+				wget -O "${F}" "${x}" || {
+					error 'Failed to download '${x}' .'
+					return 1;
+				}
+				AddResolveListFromFile "${x}" || return ${?};
+			;;
+
+			file://* )
+				x="${x:7}";
+				AddResolveListFromFile "${x}" || return ${?};
+			;;
+
+			*://* )
+				error "Unsupported protocol '${x%%://*}' specified."
+				return 1;
+			;;
+
+			./* | ../* | /*/* | ~/* | *.* )
+				AddResolveListFromFile "${x}" || return ${?};
+			;;
+
+			*/* | * )
+				[ -e "${x}" ] && {
+					AddResolveListFromFile "${x}" || return ${?};
+					continue;
+				}
+
+				FindDB "${x}" && {
+					error FOUND: $DBFOUND_FILE
+					error FOUND: $DBFOUND_DEPENDS
+				} || {
+					error "Package '${x}' is not found in local database."
+					error 'Use `dlpm /Update` to synchronize database with repositories.'
+					return 1;
+				}
+			;;
+		esac
+	done
+
+echo "
+RESOLVED:
+$DLPM_RESOLVED_FILE
+
+DEPENDS:
+$DLPM_RESOLVED_DEPENDS
+
+PROCED:
+"
+set | grep -e DLPM__DEP_ID_SOL
+
+	return 0;
+}
+
+FindDB(){ # 1 ID
+	local ID="${1}";
+	local IFS;
+	local OFS="${IFS}";
+
+	# Not local
+	DBFOUND_FILE='';
+	DBFOUND_DEPENDS='';
+
+	[ ! "${DLPM_FINDDB_INIT:-0}" = '1' ] && {
+		ConfigLoad "${REP_LIST}" DLPMReps > /dev/null || return ${?};
+		ConfigLoad "${DLP_CONFIG}" DLPConfig > /dev/null || return ${?};
+		local PF_ROOT SYS_ROOT;
+		ConfigGet PF_ROOT 'DLPConfig::DLP:Platform'
+		ConfigGet SYS_ROOT 'DLPConfig::DLP:System'
+		DLPM_FINDDB_INIT=1
+	}
+
+	local x y P;
+	for x in `ConfigListWithValue DLPMReps::Repositories`; do
+		P="${x#*=}";
+		case "${P}" in
+			*://* )
+				error Remotely access ${P}
+			;;
+
+			* )
+				error Directly access "${P}/DESLPackage.db"
+				for y in `cat "${P}/DESLPackage.db" | grep -e "${ID}|${PF_ROOT}|${SYS_ROOT}|" | sort -r -V -k2,3 -t '|'`; do
+					IFS='|';
+					set -- ${y}
+					IFS="${OFS}";
+					[ "${ID}::${PF_ROOT}::${SYS_ROOT}" = "${1}::${2}::${3}" ] && {
+						DBFOUND_FILE="${P}/${8}";
+						DBFOUND_DEPENDS="${7}";
+						return 0;
+					}
+				done
+			;;
+
+		esac
+	done
+
+	return 1;
 }
 
 error(){
